sudo: false
language: scala
scala:
- 2.11.7
script:
- sbt clean coverage test
- sbt coverageReport
after_success:
- sbt codacyCoverage
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ef2213e0d62c8d4640a3
    on_success: change
    on_failure: always
    on_start: never
before_install:
- openssl aes-256-cbc -K $encrypted_bb2d04715d29_key -iv $encrypted_bb2d04715d29_iv
  -in vcap_services.json.enc -out src/test/resources/vcap_services.json -d
